baseurl = "https://ffd-microsite-production.app.cloud.gov/"
languageCode = "en-us"
[params]
  Title = "Federal Front Door"
  Description = "The publicâ€™s front door to government services"
  Repo = "https://github.com/18F/ffd-microsite"
